'use client';

import { useEffect, useState } from 'react';
import { BarChart3, Check, Code2, Facebook, Save, ShieldCheck, Tag } from 'lucide-react';

type Scripts = { ga4: string; googleAds: string; googleAdsConversion: string; metaPixel: string; customHead: string; customBody: string; enabled: boolean; consentRequired: boolean };
const empty: Scripts = { ga4: '', googleAds: '', googleAdsConversion: '', metaPixel: '', customHead: '', customBody: '', enabled: false, consentRequired: true };

export default function SeoScriptsPage() {
  const [form, setForm] = useState<Scripts>(empty);
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const [saving, setSaving] = useState(false);
  useEffect(() => { fetch('/api/admin/seo/scripts').then(async response => { if (!response.ok) throw new Error('Não foi possível carregar a configuração.'); return response.json(); }).then(body => setForm({ ...empty, ...body })).catch(error => setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Não foi possível carregar a configuração.' })); }, []);
  async function save() { setSaving(true); setMessage(null); try { const response = await fetch('/api/admin/seo/scripts', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Não foi possível salvar.'); setMessage({ type: 'success', text: 'Scripts e pixels salvos com sucesso.' }); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'Não foi possível salvar.' }); } finally { setSaving(false); } }
  const update = (values: Partial<Scripts>) => setForm(current => ({ ...current, ...values }));
  return <main className="admin-cms tracking-page">
    <header className="admin-cms-header tracking-header"><div><span className="admin-cms-kicker">SEO / SCRIPTS E PIXELS</span><h1>Medição e conversões</h1><p>Centralize os identificadores de marketing e controle quando os scripts podem ser executados no site.</p></div><button className="admin-cms-primary" onClick={save} disabled={saving}><Save size={15}/>{saving ? 'Salvando…' : 'Salvar configuração'}</button></header>
    {message && <div className={`admin-cms-message ${message.type === 'error' ? 'error' : ''}`} role="status">{message.type === 'success' && <Check size={16}/>} {message.text}</div>}
    <section className="tracking-overview"><div><span className="tracking-kicker">CONTROLE DE DADOS</span><h2>Uma camada segura para medir campanhas</h2><p>Os identificadores ficam armazenados no painel e só são publicados quando a ativação estiver ligada.</p></div><div className={`tracking-live ${form.enabled ? 'on' : ''}`}><span />{form.enabled ? 'Medição ativa' : 'Medição desativada'}</div></section>
    <div className="tracking-layout"><div className="tracking-main">
      <section className="admin-panel-card tracking-card"><div className="tracking-card-heading"><div><span className="tracking-kicker">ANALYTICS</span><h2>Google Analytics 4</h2><p>Use o Measurement ID no formato <strong>G-XXXXXXXXXX</strong>.</p></div><BarChart3 size={24}/></div><label>Measurement ID<input value={form.ga4} placeholder="G-XXXXXXXXXX" onChange={e => update({ ga4: e.target.value.toUpperCase() })}/></label></section>
      <section className="admin-panel-card tracking-card"><div className="tracking-card-heading"><div><span className="tracking-kicker">MÍDIA PAGA</span><h2>Google Ads</h2><p>Informe o ID da conta e, se quiser acompanhar uma ação, o rótulo da conversão.</p></div><Tag size={24}/></div><div className="tracking-fields-grid"><label>ID da conversão<input value={form.googleAds} placeholder="AW-123456789" onChange={e => update({ googleAds: e.target.value })}/></label><label>Rótulo da conversão<input value={form.googleAdsConversion} placeholder="Ex.: abc123XYZ" onChange={e => update({ googleAdsConversion: e.target.value })}/></label></div></section>
      <section className="admin-panel-card tracking-card"><div className="tracking-card-heading"><div><span className="tracking-kicker">REDES SOCIAIS</span><h2>Meta Pixel</h2><p>O ID numérico conecta eventos de navegação e conversão ao Meta Ads.</p></div><Facebook size={24}/></div><label>ID do Pixel<input value={form.metaPixel} placeholder="123456789012345" onChange={e => update({ metaPixel: e.target.value.replace(/\D/g, '') })}/></label></section>
      <section className="admin-panel-card tracking-card"><div className="tracking-card-heading"><div><span className="tracking-kicker">CÓDIGO AVANÇADO</span><h2>Scripts personalizados</h2><p>Use somente códigos revisados. Eles são inseridos no HTML conforme a posição selecionada.</p></div><Code2 size={24}/></div><div className="tracking-code-grid"><label>Script adicional no HEAD<textarea value={form.customHead} placeholder="<!-- código aprovado -->" onChange={e => update({ customHead: e.target.value })}/></label><label>Script adicional no BODY<textarea value={form.customBody} placeholder="<!-- código aprovado -->" onChange={e => update({ customBody: e.target.value })}/></label></div></section>
    </div><aside className="tracking-side"><section className="admin-panel-card tracking-settings-card"><div className="tracking-card-heading"><div><span className="tracking-kicker">PUBLICAÇÃO</span><h2>Regras de execução</h2></div><ShieldCheck size={22}/></div><label className="tracking-toggle"><input type="checkbox" checked={form.enabled} onChange={e => update({ enabled: e.target.checked })}/><span><strong>Ativar scripts</strong><small>Publicar os códigos no site.</small></span></label><label className="tracking-toggle"><input type="checkbox" checked={form.consentRequired} onChange={e => update({ consentRequired: e.target.checked })}/><span><strong>Exigir consentimento</strong><small>Aguardar consentimento antes de medir.</small></span></label><div className="tracking-note"><strong>Recomendação</strong><p>Mantenha o consentimento ativo para respeitar a escolha de privacidade das pessoas visitantes.</p></div></section><section className="tracking-help"><strong>Antes de publicar</strong><p>Confira os IDs no painel de cada provedor. Um identificador incorreto pode gerar dados incompletos ou atribuições erradas.</p></section></aside></div>
  </main>;
}
