'use client';
import { useEffect, useState } from 'react';

type Article = { id: string; slug: string; title: string; excerpt: string | null; content: string; status: string; publishedAt: string | null; categoryId?: string | null; category?: { id: string; name: string; slug: string } | null };
type Category = { id: string; name: string; slug: string };
export default function BlogAdminPage() { const [items, setItems] = useState<Article[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [form, setForm] = useState({ title: '', slug: '', excerpt: '', content: '', categoryId: '' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [updatingId, setUpdatingId] = useState('');
  async function load() { const response = await fetch('/api/admin/content?kind=article'); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Não foi possível carregar artigos.'); setItems(body.data); }
  useEffect(() => { load().catch(e => setError(e instanceof Error ? e.message : 'Não foi possível carregar artigos.')); fetch('/api/admin/categories').then(r => r.json()).then(body => setCategories(body.data || [])).catch(() => setError('Não foi possível carregar categorias.')); }, []);
  async function create() { setSaving(true); setError(''); try { const response = await fetch('/api/admin/content', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Não foi possível criar o artigo.'); setForm({ title: '', slug: '', excerpt: '', content: '', categoryId: '' }); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao criar o artigo.'); } finally { setSaving(false); } }
  async function update(item: Article, status: string) { setUpdatingId(item.id); setError(''); try { const response = await fetch(`/api/admin/content/${item.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: 'article', status }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Não foi possível atualizar o artigo.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao atualizar o artigo.'); } finally { setUpdatingId(''); } }
  return <main className="admin-cms"><header className="admin-cms-header"><div><span className="admin-cms-kicker">CONTEÚDO / BLOG</span><h1>Artigos</h1><p>Publique materiais educativos sem inventar métricas.</p></div></header>{error && <div className="admin-cms-message error">{error}</div>}<section className="admin-cms-card"><h2>Novo artigo</h2><div className="admin-form-grid"><label>Título<input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })}/></label><label>Categoria<select value={form.categoryId} onChange={e => setForm({ ...form, categoryId: e.target.value })}><option value="">Sem categoria</option>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Slug<input value={form.slug} onChange={e => setForm({ ...form, slug: e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, '-') })}/></label><label className="wide">Resumo<textarea rows={2} value={form.excerpt} onChange={e => setForm({ ...form, excerpt: e.target.value })}/></label><label className="wide">Conteúdo em texto simples<textarea rows={6} value={form.content} onChange={e => setForm({ ...form, content: e.target.value })}/></label></div><button className="admin-cms-primary" onClick={create} disabled={saving || !form.title.trim() || !form.slug.trim() || !form.content.trim()}>{saving ? 'Criando…' : 'Criar rascunho'}</button></section><section className="admin-cms-card"><h2>Publicações</h2><div className="admin-order-table"><table><thead><tr><th>Título</th><th>Categoria</th><th>Slug</th><th>Status</th><th>Ações</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><strong>{item.title}</strong><small>{item.excerpt || 'Sem resumo'}</small></td><td>{item.category?.name || 'Sem categoria'}</td><td>{item.slug}</td><td><span className={`admin-order-status ${item.status.toLowerCase()}`}>{item.status}</span></td><td><div className="admin-table-actions"><button onClick={() => update(item, item.status === 'PUBLISHED' ? 'DRAFT' : 'PUBLISHED')} disabled={updatingId === item.id}>{updatingId === item.id ? 'Atualizando…' : item.status === 'PUBLISHED' ? 'Despublicar' : 'Publicar'}</button></div></td></tr>)}{items.length === 0 && <tr><td colSpan={4}>Nenhum artigo cadastrado.</td></tr>}</tbody></table></div></section></main>;
}
