'use client';

import Link from 'next/link';
import { ArrowLeft, Check, LoaderCircle } from 'lucide-react';
import { FormEvent, useState } from 'react';

export default function ResetPasswordPage() {
  const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setMessage(''); if (password !== confirmation) { setError('As senhas não coincidem.'); return; } setLoading(true); try { const token = new URLSearchParams(window.location.search).get('token') || ''; const response = await fetch('/api/auth/reset-password', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token, password }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setMessage(body.message); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível redefinir a senha.'); } finally { setLoading(false); } }
  return <section className="auth-page"><div className="auth-box"><Link href="/login" className="auth-back"><ArrowLeft size={15}/> Voltar para o login</Link><span className="eyebrow">Segurança da conta</span><h1>Crie uma nova senha.</h1><p>Escolha uma senha com pelo menos 8 caracteres.</p><form onSubmit={submit}><label>Nova senha<input required minLength={8} type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password"/></label><label>Confirmar senha<input required minLength={8} type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="new-password"/></label>{error && <p className="auth-message auth-error">{error}</p>}{message && <p className="auth-message auth-success"><Check size={16}/>{message}</p>}<button className="button" disabled={loading || Boolean(message)}>{loading ? <LoaderCircle className="spin" size={17}/> : <Check size={17}/>} Salvar nova senha</button></form>{message && <Link href="/login" className="auth-change">Entrar agora</Link>}</div></section>;
}
