'use client';

import { FormEvent, useEffect, useState } from 'react';
import { AdminPageHeader } from '@/components/admin-primitives';
import { BellRing, Check, LoaderCircle, Plus, Shield, Trash2, UserRound, X } from 'lucide-react';

type InternalUser = { id: string; name: string | null; email: string | null; role: 'ADMIN' | 'SUPERADMIN'; createdAt: string; notifyNewConsultationOrders: boolean; notifyConsultationStatusChanges: boolean; notifySystemAlerts: boolean };
type Preference = 'notifyNewConsultationOrders' | 'notifyConsultationStatusChanges' | 'notifySystemAlerts';
const preferenceLabels: { key: Preference; label: string; description: string }[] = [
  { key: 'notifyNewConsultationOrders', label: 'Novos pedidos de consulta', description: 'Preferência para alertas de pedidos recém-criados.' },
  { key: 'notifyConsultationStatusChanges', label: 'Mudanças de status', description: 'Preferência para atualizações no andamento das consultas.' },
  { key: 'notifySystemAlerts', label: 'Alertas do sistema', description: 'Preferência para avisos operacionais e de configuração.' },
];

export default function AdminUsersPage() {
  const [users, setUsers] = useState<InternalUser[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [newPreferences, setNewPreferences] = useState<Record<Preference, boolean>>({ notifyNewConsultationOrders: false, notifyConsultationStatusChanges: false, notifySystemAlerts: false }); const [pending, setPending] = useState('');
  async function load() { setLoading(true); try { const response = await fetch('/api/admin/users'); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Não foi possível carregar usuários.'); setUsers(body.data); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível carregar usuários.'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function create(event: FormEvent) { event.preventDefault(); setError(''); setSuccess(''); setSaving(true); try { const response = await fetch('/api/admin/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, email, password, ...newPreferences }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Não foi possível criar usuário.'); setName(''); setEmail(''); setPassword(''); setNewPreferences({ notifyNewConsultationOrders: false, notifyConsultationStatusChanges: false, notifySystemAlerts: false }); setSuccess('Usuário interno criado. As preferências ficam salvas até a ativação do envio de notificações.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível criar usuário.'); } finally { setSaving(false); } }
  async function toggle(user: InternalUser, key: Preference) { setPending(`${user.id}:${key}`); setError(''); setSuccess(''); const nextValue = !user[key]; setUsers((current) => current.map((entry) => entry.id === user.id ? { ...entry, [key]: nextValue } : entry)); try { const response = await fetch(`/api/admin/users/${user.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ [key]: nextValue }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Não foi possível atualizar a preferência.'); setUsers((current) => current.map((entry) => entry.id === user.id ? body.data : entry)); } catch (e) { setUsers((current) => current.map((entry) => entry.id === user.id ? { ...entry, [key]: !nextValue } : entry)); setError(e instanceof Error ? e.message : 'Não foi possível atualizar a preferência.'); } finally { setPending(''); } }
  async function resetPassword(id: string) { setPending(id); setError(''); setSuccess(''); try { const response = await fetch(`/api/admin/users/${id}/reset-password`, { method: 'POST' }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setSuccess(`Senha temporária: ${body.data.temporaryPassword}`); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível resetar a senha.'); } finally { setPending(''); } }
  async function remove(user: InternalUser) { if (!window.confirm(`Excluir o acesso de ${user.name || user.email}?`)) return; setPending(user.id); setError(''); setSuccess(''); try { const response = await fetch(`/api/admin/users/${user.id}`, { method: 'DELETE' }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Não foi possível excluir o usuário.'); setUsers((current) => current.filter((entry) => entry.id !== user.id)); setSuccess('Acesso interno removido.'); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível excluir o usuário.'); } finally { setPending(''); } }

  return <div className="admin-users-page"><AdminPageHeader eyebrow="Sistema / Usuários" title="Usuários internos" description="Gerencie quem pode acessar a administração e as preferências de comunicação."/><div className="admin-users-notice"><BellRing size={18}/><div><strong>Preferências preparadas para notificações</strong><p>As categorias ficam salvas por usuário. O envio de alertas por e-mail será ativado quando os eventos do sistema forem conectados.</p></div></div>{error && <div className="admin-users-feedback error" role="alert"><X size={16}/>{error}</div>}{success && <div className="admin-users-feedback success" role="status"><Check size={16}/>{success}</div>}
    <section className="admin-panel-card admin-users-create"><div className="admin-card-heading"><div><span className="admin-eyebrow">NOVO ACESSO</span><h2>Adicionar usuário interno</h2><p>Será criada uma conta ADMIN. O acesso SUPERADMIN continua restrito.</p></div></div><form onSubmit={create}><div className="admin-form-grid"><label>Nome completo<input required maxLength={100} value={name} onChange={(e) => setName(e.target.value)} autoComplete="name"/></label><label>E-mail de acesso<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} autoComplete="email"/></label><label>Senha inicial<input required type="password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="new-password"/><small className="table-muted">Mínimo de 8 caracteres. Compartilhe com segurança.</small></label></div><div className="admin-users-new-prefs"><strong>Preferências de notificação</strong><div className="admin-users-pref-grid">{preferenceLabels.map(({ key, label, description }) => <label key={key} className="admin-users-pref"><input type="checkbox" checked={newPreferences[key]} onChange={(e) => setNewPreferences((current) => ({ ...current, [key]: e.target.checked }))}/><span><b>{label}</b><small>{description}</small></span></label>)}</div></div><button className="admin-primary-button" disabled={saving}>{saving ? <LoaderCircle size={15} className="spin"/> : <Plus size={15}/>} Criar acesso ADMIN</button></form></section>
    <section className="admin-panel-card admin-users-list"><div className="admin-card-heading"><div><span className="admin-eyebrow">ACESSOS ATIVOS</span><h2>Equipe administrativa</h2><p>{users.length} usuário(s) interno(s)</p></div><span className="admin-users-privacy"><Shield size={15}/> Dados restritos a SUPERADMIN</span></div>{loading ? <div className="admin-users-loading"><LoaderCircle className="spin"/> Carregando usuários…</div> : users.length === 0 ? <div className="admin-users-empty"><UserRound size={24}/><strong>Nenhum usuário interno</strong><span>Crie um acesso para começar a organizar a equipe.</span></div> : <div className="admin-table-wrap"><table className="admin-table admin-users-table"><thead><tr><th>Usuário</th><th>Papel</th><th>Notificações (preferências)</th><th>Criado em</th><th>Ações</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><strong>{user.name || 'Sem nome'}</strong><small className="table-muted">{user.email}</small></td><td><span className={`admin-users-role ${user.role.toLowerCase()}`}>{user.role === 'SUPERADMIN' ? 'Superadmin' : 'Admin'}</span></td><td><div className="admin-users-toggle-list">{preferenceLabels.map(({ key, label }) => <label className="admin-users-toggle" key={key}><input type="checkbox" checked={user[key]} disabled={pending === `${user.id}:${key}`} onChange={() => toggle(user, key)}/><span className="admin-users-switch"/><span>{label}</span></label>)}</div></td><td>{new Date(user.createdAt).toLocaleDateString('pt-BR')}</td><td><button className="admin-users-reset" onClick={() => resetPassword(user.id)} disabled={Boolean(pending)}>Resetar senha</button><button className="admin-users-delete" onClick={() => remove(user)} disabled={Boolean(pending)} aria-label={`Excluir ${user.name || user.email}`}><Trash2 size={15}/> Excluir</button></td></tr>)}</tbody></table></div>}</section>
  </div>;
}
