import Link from 'next/link';
import { ArrowRight, Plus, Search, Users, Package, FileSearch, ShoppingCart } from 'lucide-react';
import { AdminPageHeader, EmptyState, KpiCard, StatusBadge } from '@/components/admin-primitives';

const products = [
  { name: 'Consulta Premium', slug: 'consulta-premium', price: 'R$ 59,90', status: 'Publicado', sales: '94', feature: true },
  { name: 'Consulta Essencial', slug: 'consulta-essencial', price: 'R$ 19,90', status: 'Publicado', sales: '61', feature: false },
  { name: 'Dados Cadastrais + Roubo e Furto', slug: 'roubo-furto', price: 'R$ 14,90', status: 'Publicado', sales: '38', feature: false },
  { name: 'Dados Atuais do Veículo', slug: 'dados-veiculo', price: 'R$ 12,90', status: 'Rascunho', sales: '22', feature: false },
  { name: 'Consulta de Financiamento', slug: 'financiamento', price: 'R$ 16,90', status: 'Publicado', sales: '17', feature: false }
];
const customers = [{ name: 'Mariana Costa', email: 'mariana@email.com', phone: '(11) 99812-4432', purchases: '4', spent: 'R$ 219,60', status: 'Ativo' }, { name: 'Rafael Nunes', email: 'rafael@email.com', phone: '(21) 99124-7701', purchases: '2', spent: 'R$ 79,80', status: 'Ativo' }, { name: 'Camila Alves', email: 'camila@email.com', phone: '(31) 98872-1520', purchases: '1', spent: 'R$ 12,90', status: 'Novo' }];
const consultations = [{ id: '#CON-0184', plate: 'ABC1D23', customer: 'Mariana Costa', product: 'Consulta Premium', provider: 'DataCheck', status: 'Concluída', time: '1,8s' }, { id: '#CON-0183', plate: 'QWE4R56', customer: 'Rafael Nunes', product: 'Consulta Essencial', provider: 'DataCheck', status: 'Processando', time: '—' }, { id: '#CON-0182', plate: 'JKL9M01', customer: 'Camila Alves', product: 'Dados do veículo', provider: 'AutoDados', status: 'Erro', time: '12,4s' }];
const abandoned = [{ name: 'João Pereira', contact: 'joao@email.com', plate: 'MNO2P34', product: 'Consulta Premium', value: 'R$ 59,90', stage: 'PIX gerado', time: '37 min', recovery: 'Novo' }, { name: 'Lead sem identificação', contact: '—', plate: 'RTY5U67', product: 'Consulta Essencial', value: 'R$ 19,90', stage: 'Produto selecionado', time: '2h', recovery: 'Aguardando contato' }, { name: 'Ana Beatriz', contact: 'ana@email.com', plate: 'FGH8I90', product: 'Consulta Premium', value: 'R$ 59,90', stage: 'Checkout', time: '5h', recovery: 'Contatado' }];

export function AdminProductsPage() { return <><AdminPageHeader eyebrow="Produtos" title="Consultas veiculares" description="Gerencie produtos, preços, características e como aparecem no site." action={<button className="admin-primary-button"><Plus size={16}/> Novo produto</button>}/><section className="admin-kpi-grid"><KpiCard label="Produtos ativos" value="4" detail="1 em rascunho"/><KpiCard label="Vendas no período" value="232" change="14,2%"/><KpiCard label="Produto em destaque" value="Premium" detail="Consulta Premium"/><KpiCard label="Ticket médio" value="R$ 32,46" change="5,8%"/></section><section className="admin-panel-card"><div className="admin-toolbar"><div className="admin-search"><Search size={16}/><input placeholder="Buscar produto..."/></div><select aria-label="Filtro de status"><option>Todos os status</option><option>Publicado</option><option>Rascunho</option></select></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Produto</th><th>Preço</th><th>Status</th><th>Destaque</th><th>Vendas</th><th>Conversão</th><th>Ação</th></tr></thead><tbody>{products.map((product) => <tr key={product.slug}><td><strong>{product.name}</strong><small className="table-muted">/{product.slug}</small></td><td>{product.price}</td><td><StatusBadge status={product.status} tone={product.status === 'Publicado' ? 'success' : 'neutral'}/></td><td>{product.feature ? <span className="green-text">Sim</span> : '—'}</td><td>{product.sales}</td><td>18,7%</td><td><Link className="table-action" href={`/admin/produtos/${product.slug}`}>Editar <ArrowRight size={14}/></Link></td></tr>)}</tbody></table></div></section></>; }

export function AdminProductEditPage({ slug }: { slug: string }) { const product = products.find((item) => item.slug === slug) || products[0]; return <><AdminPageHeader eyebrow="Produtos / Editar" title={product.name} description="Atualize o produto sem duplicar informações no site." action={<div className="page-actions"><button className="admin-secondary-button">Visualizar <ArrowRight size={15}/></button><button className="admin-primary-button">Publicar</button></div>}/><div className="admin-editor-layout"><nav className="editor-tabs"><a className="active" href="#geral">Geral</a><a href="#conteudo">Conteúdo</a><a href="#caracteristicas">Características</a><a href="#preco">Preço</a><a href="#relatorio">Relatório</a><a href="#faq">FAQ</a><a href="#seo">SEO</a><a href="#exibicao">Exibição</a></nav><section className="admin-panel-card editor-card"><div className="editor-section" id="geral"><div className="admin-card-heading"><div><span className="admin-eyebrow">Informações principais</span><h2>Dados gerais</h2></div></div><div className="admin-form-grid"><label>Nome do produto<input defaultValue={product.name}/></label><label>Slug<input defaultValue={product.slug}/></label><label className="wide">Descrição curta<textarea defaultValue="Uma consulta demonstrativa para ajudar você a analisar melhor um veículo." rows={3}/></label><label>Status<select defaultValue={product.status}><option>Publicado</option><option>Rascunho</option><option>Arquivado</option></select></label><label>Código interno<input defaultValue={`OD-${product.slug.toUpperCase()}`}/></label></div></div><div className="editor-section" id="preco"><div className="admin-card-heading"><div><span className="admin-eyebrow">Comercial</span><h2>Preço e promoção</h2></div></div><div className="admin-form-grid"><label>Preço normal<input defaultValue={product.price}/></label><label>Preço promocional<input placeholder="Opcional"/></label><label>Início da promoção<input type="datetime-local"/></label><label>Fim da promoção<input type="datetime-local"/></label></div></div><div className="editor-section" id="caracteristicas"><div className="admin-card-heading"><div><span className="admin-eyebrow">Informação do relatório</span><h2>Características incluídas</h2></div></div><div className="feature-checks">{['Dados cadastrais', 'Leilão', 'Sinistro', 'Roubo e furto', 'Restrições', 'Gravame', 'Financiamento', 'Recall'].map((feature, index) => <label key={feature}><input type="checkbox" defaultChecked={index < 4}/><span>{feature}</span></label>)}</div></div></section></div></>; }

export function AdminCustomersPage() { return <><AdminPageHeader eyebrow="Comercial" title="Clientes" description="Veja quem compra, consulta e retorna ao Olho no Doc."/><section className="admin-kpi-grid"><KpiCard label="Total de clientes" value="1.284" change="9,4%"/><KpiCard label="Novos hoje" value="32"/><KpiCard label="Clientes recorrentes" value="186" change="12,1%"/><KpiCard label="Abandonaram" value="74" positive={false} detail="Precisam de atenção"/></section><section className="admin-panel-card"><div className="admin-toolbar"><div className="admin-search"><Search size={16}/><input placeholder="Buscar por nome, e-mail, telefone ou CPF..."/></div><button className="admin-secondary-button">Filtros <ChevronFilter/></button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Cliente</th><th>Telefone</th><th>Compras</th><th>Total gasto</th><th>Última compra</th><th>Status</th><th/></tr></thead><tbody>{customers.map((customer) => <tr key={customer.email}><td><strong>{customer.name}</strong><small className="table-muted">{customer.email}</small></td><td>{customer.phone}</td><td>{customer.purchases}</td><td>{customer.spent}</td><td>Hoje, 14:32</td><td><StatusBadge status={customer.status} tone="success"/></td><td><button className="table-action">Ver <ArrowRight size={14}/></button></td></tr>)}</tbody></table></div></section></>; }
function ChevronFilter() { return <span className="filter-icon">⌄</span>; }

export function AdminConsultationsPage() { return <><AdminPageHeader eyebrow="Operação" title="Consultas realizadas" description="Acompanhe o processamento, desempenho e erros dos fornecedores."/><section className="admin-kpi-grid"><KpiCard label="Hoje" value="94" change="12,8%"/><KpiCard label="Concluídas" value="89"/><KpiCard label="Processando" value="2" detail="Agora"/><KpiCard label="Com erro" value="3" positive={false} detail="Revisar"/></section><section className="admin-panel-card"><div className="admin-toolbar"><div className="admin-search"><Search size={16}/><input placeholder="Buscar por ID, placa ou cliente..."/></div><select aria-label="Filtro de consultas"><option>Todos os status</option><option>Concluída</option><option>Processando</option><option>Erro</option></select></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>ID</th><th>Placa</th><th>Cliente</th><th>Produto</th><th>Fornecedor</th><th>Tempo</th><th>Status</th><th/></tr></thead><tbody>{consultations.map((consultation) => <tr key={consultation.id}><td><strong>{consultation.id}</strong></td><td>{consultation.plate}</td><td>{consultation.customer}</td><td>{consultation.product}</td><td>{consultation.provider}</td><td>{consultation.time}</td><td><StatusBadge status={consultation.status} tone={consultation.status === 'Concluída' ? 'success' : consultation.status === 'Erro' ? 'danger' : 'warning'}/></td><td><button className="table-action">Detalhes <ArrowRight size={14}/></button></td></tr>)}</tbody></table></div></section></>; }

export function AdminAbandonedPage() { return <><AdminPageHeader eyebrow="Comercial" title="Carrinhos abandonados" description="Entenda onde a compra parou e aja sobre as oportunidades de recuperação." action={<button className="admin-secondary-button">Exportar <ArrowRight size={15}/></button>}/><section className="admin-kpi-grid"><KpiCard label="Abandonados hoje" value="39"/><KpiCard label="Valor potencial" value="R$ 2.143,60"/><KpiCard label="Recuperados" value="13" change="8,4%"/><KpiCard label="Receita recuperada" value="R$ 786,20" change="12,7%"/></section><section className="admin-panel-card"><div className="admin-toolbar"><div className="admin-search"><Search size={16}/><input placeholder="Buscar por cliente, placa ou produto..."/></div><select aria-label="Filtro de recuperação"><option>Todos</option><option>Novo</option><option>Contatado</option><option>Recuperado</option></select></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Cliente / lead</th><th>Placa</th><th>Produto</th><th>Valor</th><th>Etapa</th><th>Abandono</th><th>Recuperação</th><th/></tr></thead><tbody>{abandoned.map((item) => <tr key={item.plate}><td><strong>{item.name}</strong><small className="table-muted">{item.contact}</small></td><td>{item.plate}</td><td>{item.product}</td><td>{item.value}</td><td>{item.stage}</td><td>{item.time}</td><td><StatusBadge status={item.recovery} tone={item.recovery === 'Novo' ? 'warning' : item.recovery === 'Contatado' ? 'neutral' : 'success'}/></td><td><button className="table-action">Abrir <ArrowRight size={14}/></button></td></tr>)}</tbody></table></div></section></>; }

export function AdminPlaceholderPage({ title, section }: { title: string; section: string }) { return <><AdminPageHeader eyebrow={section} title={title} description="Estrutura preparada para conectar dados reais do PostgreSQL e as permissões da operação."/><section className="admin-panel-card placeholder-panel"><EmptyState title="Módulo preparado" description="A interface está pronta para receber os registros reais. Nenhuma ação foi simulada." action={<button className="admin-primary-button">Configurar módulo <ArrowRight size={15}/></button>}/></section></>; }

export function AdminBrandPage() { return <><AdminPageHeader eyebrow="Sistema / Marca" title="Identidade da marca" description="Centralize a identidade e os contatos exibidos pelo Olho no Doc." action={<button className="admin-primary-button">Salvar alterações</button>}/><div className="admin-editor-layout"><section className="admin-panel-card editor-card"><div className="editor-section"><div className="admin-card-heading"><div><span className="admin-eyebrow">Identidade visual</span><h2>Logo oficial</h2></div></div><div className="brand-preview"><img src="/logo-olho-no-doc.png" alt="Prévia da logo Olho no Doc"/><span>Logo principal · PNG</span></div><div className="admin-form-grid"><label>Nome da marca<input defaultValue="Olho no Doc"/></label><label>Slogan<input defaultValue="Sua tranquilidade é nosso foco."/></label><label>Cor principal<input defaultValue="#071B33"/></label><label>Cor de ação<input defaultValue="#007332"/></label></div></div><div className="editor-section"><div className="admin-card-heading"><div><span className="admin-eyebrow">Canais oficiais</span><h2>Informações institucionais</h2></div></div><div className="admin-form-grid"><label>E-mail<input placeholder="contato@seudominio.com"/></label><label>Telefone<input placeholder="(00) 00000-0000"/></label><label>WhatsApp<input placeholder="(00) 00000-0000"/></label><label>CNPJ<input placeholder="Não informado"/></label><label className="wide">Endereço<textarea rows={3} placeholder="Adicione somente dados oficiais."/></label></div></div></section><aside className="admin-side-note"><span className="admin-eyebrow">Fonte única</span><h3>Uma alteração, todos os lugares.</h3><p>Esses dados serão usados no site público, rodapé e configurações futuras sem duplicar conteúdo.</p></aside></div></>; }

export function AdminHomeCmsPage() { return <><AdminPageHeader eyebrow="Site / Home" title="Conteúdo da Home" description="Organize as seções públicas sem alterar o layout base." action={<div className="page-actions"><button className="admin-secondary-button">Pré-visualizar <ArrowRight size={15}/></button><button className="admin-primary-button">Publicar</button></div>}/><section className="admin-panel-card"><div className="cms-section-list">{['Hero principal', 'Benefícios', 'Consulta Premium', 'Preview de relatório', 'Como funciona', 'Consultas disponíveis', 'Bloco humanizado', 'Blog', 'FAQ', 'CTA final'].map((name, index) => <div className="cms-section-row" key={name}><span className="drag-handle">☰</span><div><strong>{name}</strong><small>{index === 0 ? 'Título, subtítulo, campo de placa e CTA' : index === 2 ? 'Produto selecionado automaticamente' : 'Conteúdo ativo no site'}</small></div><label className="switch"><input type="checkbox" defaultChecked/><i/></label><button className="table-action">Editar <ArrowRight size={14}/></button></div>)}</div></section></>; }

export function AdminPagesCmsPage() { return <><AdminPageHeader eyebrow="Site / Páginas" title="Páginas do site" description="Controle status, SEO e publicação das páginas públicas." action={<button className="admin-primary-button"><Plus size={16}/> Nova página</button>}/><section className="admin-panel-card"><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Página</th><th>Slug</th><th>Status</th><th>SEO</th><th>Atualização</th><th>Ação</th></tr></thead><tbody>{[['Home','/','Publicado','Completo'],['Consultas','/consultas','Publicado','Completo'],['Como funciona','/como-funciona','Publicado','Revisar'],['Preços','/precos','Publicado','Completo'],['Sobre','/sobre','Rascunho','Pendente'],['Contato','/contato','Publicado','Completo']].map(([name, slug, status, seo]) => <tr key={slug}><td><strong>{name}</strong></td><td>{slug}</td><td><StatusBadge status={status} tone={status === 'Publicado' ? 'success' : 'neutral'}/></td><td><StatusBadge status={seo} tone={seo === 'Completo' ? 'success' : 'warning'}/></td><td>Hoje, 10:24</td><td><button className="table-action">Editar <ArrowRight size={14}/></button></td></tr>)}</tbody></table></div></section></>; }

export function AdminMenuCmsPage() { return <><AdminPageHeader eyebrow="Site / Menu" title="Menu principal" description="Organize links, submenus e destinos da navegação pública." action={<button className="admin-primary-button"><Plus size={16}/> Adicionar item</button>}/><section className="admin-panel-card"><div className="cms-section-list">{['Consultas', '  Consulta Premium', '  Consulta Essencial', '  Roubo e furto', '  Dados do veículo', '  Financiamento', 'Como funciona', 'Exemplo de relatório', 'Preços', 'Conteúdos'].map((name, index) => <div className={`cms-section-row ${index > 0 && index < 6 ? 'nested-row' : ''}`} key={`${name}-${index}`}><span className="drag-handle">☰</span><div><strong>{name}</strong><small>{index === 0 ? 'Submenu · 5 itens' : 'Link interno'}</small></div><button className="table-action">Editar <ArrowRight size={14}/></button></div>)}</div></section></>; }

export function AdminMediaPage() { return <><AdminPageHeader eyebrow="Site / Mídias" title="Biblioteca de mídias" description="Centralize logos, imagens e materiais usados no site." action={<button className="admin-primary-button"><Plus size={16}/> Enviar mídia</button>}/><section className="admin-panel-card"><div className="admin-toolbar"><div className="admin-search"><Search size={16}/><input placeholder="Buscar por nome ou tipo..."/></div><select aria-label="Categoria de mídia"><option>Todas as categorias</option><option>Logos</option><option>Site</option><option>Produtos</option><option>Blog</option></select></div><div className="media-grid"><div className="media-tile"><img src="/logo-olho-no-doc.png" alt="Logo Olho no Doc"/><strong>logo-olho-no-doc.png</strong><small>PNG · 919 × 655</small></div><div className="media-upload"><Plus size={20}/><strong>Adicionar arquivo</strong><small>PNG, JPG ou WebP</small></div></div></section></>; }
