'use client';
import { useEffect, useState } from 'react';

type RecoveryOrder = { id: string; plate: string; status: string; amountCents: number; totalCents: number | null; createdAt: string; product: { name: string }; customer: { name: string | null; email: string } | null };
const currency = (cents: number) => (cents / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
const contactLink = (order: RecoveryOrder) => order.customer?.email ? `mailto:${order.customer.email}?subject=${encodeURIComponent(`Pedido ${order.id.slice(-8).toUpperCase()} ainda disponível`)}` : undefined;
export default function RecoveryActionsPage() { const [pending, setPending] = useState<RecoveryOrder[]>([]); const [error, setError] = useState(''); const [done, setDone] = useState<string[]>([]);
  useEffect(() => { fetch('/api/admin/recovery').then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setPending(body.data.pending); }).catch(e => setError(e.message)); }, []);
  return <main className="admin-cms"><header className="admin-cms-header"><div><span className="admin-cms-kicker">COMERCIAL / RECUPERAÇÃO</span><h1>Recuperações</h1><p>Priorize contatos e marque pedidos como tratados.</p></div></header>{error && <div className="admin-cms-message error">{error}</div>}<section className="admin-cms-card"><h2>Fila de recuperação</h2><div className="admin-order-table"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Valor</th><th>Pedido criado</th><th>Ação</th></tr></thead><tbody>{pending.map(order => <tr key={order.id}><td><strong>{order.id.slice(-8).toUpperCase()}</strong><small>{order.product.name} · {order.plate}</small></td><td>{order.customer?.name || 'Cliente'}<small>{order.customer?.email || 'Sem e-mail'}</small></td><td><strong>{currency(order.totalCents ?? order.amountCents)}</strong></td><td>{new Date(order.createdAt).toLocaleString('pt-BR')}</td><td><div className="admin-table-actions">{contactLink(order) && <a className="admin-cms-primary" href={contactLink(order)}>Contatar</a>}<button onClick={() => setDone(current => [...current, order.id])}>{done.includes(order.id) ? 'Tratado ✓' : 'Marcar tratado'}</button></div></td></tr>)}{pending.length === 0 && <tr><td colSpan={5}>Nenhum pedido pendente para recuperar.</td></tr>}</tbody></table></div></section></main>;
}
