'use client';
import { useEffect, useMemo, useState } from 'react';

type Order = { id: string; plate: string; status: string; amountCents: number; subtotalCents: number | null; discountCents: number; totalCents: number | null; createdAt: string; product: { name: string; slug: string }; customer: { name: string | null; email: string } | null; coupon: { code: string } | null };
const currency = (cents: number) => (cents / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
export default function AdminOrdersPage() { const [orders, setOrders] = useState<Order[]>([]); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  async function load() { setLoading(true); setError(''); try { const response = await fetch(`/api/admin/orders${status ? `?status=${status}` : ''}`); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || 'Não foi possível carregar pedidos'); setOrders(body.data); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao carregar pedidos'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [status]);
  async function update(order: Order, next: string) { const response = await fetch('/api/admin/orders', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: order.id, status: next }) }); const body = await response.json().catch(() => ({})); if (!response.ok) { setError(body.error || 'Não foi possível atualizar'); return; } await load(); }
  const total = useMemo(() => orders.reduce((sum, order) => sum + (order.totalCents ?? order.amountCents), 0), [orders]);
  return <main className="admin-cms"><header className="admin-cms-header"><div><span className="admin-cms-kicker">VENDAS / OPERAÇÃO</span><h1>Pedidos</h1><p>Consulte pedidos, status, clientes e valores.</p></div><select className="admin-input admin-order-filter" value={status} onChange={e => setStatus(e.target.value)}><option value="">Todos os status</option><option value="PENDING">Pendente</option><option value="PAID">Pago</option><option value="COMPLETED">Concluído</option><option value="CANCELLED">Cancelado</option></select></header><div className="admin-order-summary">{orders.length} pedido(s) nesta página <strong>{currency(total)}</strong></div>{error && <div className="admin-cms-message error">{error}</div>}<div className="admin-order-table"><table><thead><tr><th>Pedido / data</th><th>Cliente</th><th>Produto / placa</th><th>Cupom</th><th>Subtotal</th><th>Desconto</th><th>Total</th><th>Status</th><th>Atualizar</th></tr></thead><tbody>{!loading && orders.map(order => <tr key={order.id}><td><strong>{order.id.slice(-8).toUpperCase()}</strong><small>{new Date(order.createdAt).toLocaleString('pt-BR')}</small></td><td>{order.customer?.name || 'Cliente'}<small>{order.customer?.email || '—'}</small></td><td>{order.product.name}<small>{order.plate}</small></td><td>{order.coupon?.code || '—'}</td><td>{currency(order.subtotalCents ?? order.amountCents)}</td><td>{currency(order.discountCents)}</td><td><strong>{currency(order.totalCents ?? order.amountCents)}</strong></td><td><span className={`admin-order-status ${order.status.toLowerCase()}`}>{order.status}</span></td><td><select aria-label="Atualizar status" value={order.status} onChange={e => update(order, e.target.value)}><option value="PENDING">Pendente</option><option value="PAID">Pago</option><option value="COMPLETED">Concluído</option><option value="CANCELLED">Cancelado</option></select></td></tr>)}{!loading && orders.length === 0 && <tr><td colSpan={9}>Nenhum pedido encontrado.</td></tr>}{loading && <tr><td colSpan={9}>Carregando pedidos…</td></tr>}</tbody></table></div></main>;
}
