import Link from 'next/link';
import { ArrowRight, Check, ChevronRight, CircleCheck, FileSearch, LockKeyhole, ScanLine } from 'lucide-react';
import { FAQ, PlateInput, ProductCard, ReportPreview } from '@/components/site';
import { products } from '@/data/products';

const faqs = ['O que é uma consulta veicular?', 'Preciso informar o Renavam?', 'Quanto tempo leva para receber o resultado?', 'Como recebo minha consulta?', 'Posso consultar qualquer veículo?', 'A consulta substitui uma vistoria cautelar?'];

export default function Home() { return <>
  <section className="hero"><div className="hero-inner"><div className="hero-copy"><div className="eyebrow eyebrow-light"><span className="eyebrow-dot"/> Inteligência para sua decisão</div><h1>Antes de comprar um veículo, descubra o que a <em>placa</em> não conta.</h1><p>Consulte informações importantes sobre o veículo em poucos segundos e tenha mais segurança antes de fechar negócio.</p><PlateInput/><div className="hero-trust"><span><Check size={14}/> Resultado online</span><span><LockKeyhole size={14}/> Consulta segura</span><span><Check size={14}/> Sem burocracia</span></div></div><div className="hero-visual"><div className="data-orbit orbit-one"/><div className="data-orbit orbit-two"/><div className="car-photo"/><div className="plate-float"><span>BR</span><strong>ABC1D23</strong></div><div className="scan-card"><div className="scan-head"><span className="live-dot"/> Consulta encontrada</div><div className="scan-item"><span>Dados cadastrais</span><CircleCheck size={17}/></div><div className="scan-item"><span>Leilão</span><CircleCheck size={17}/></div><div className="scan-item warning"><span>Restrições</span><span>!</span></div></div><span className="visual-caption">Placa fictícia · resultado demonstrativo</span></div></div></section>
  <section className="trust-strip"><div><ScanLine size={22}/><span><strong>Consulta por placa</strong><small>Comece com o que você já tem</small></span></div><div><FileSearch size={22}/><span><strong>Informação organizada</strong><small>Resultado claro e direto</small></span></div><div><LockKeyhole size={22}/><span><strong>Decisão mais segura</strong><small>Antes de fechar negócio</small></span></div></section>
  <section className="section benefits"><div className="section-heading"><div><span className="eyebrow">O que você pode verificar</span><h2>Conheça o veículo além da aparência.</h2></div><p>Uma consulta ajuda a reunir informações para você fazer perguntas melhores e negociar com mais clareza.</p></div><div className="benefit-grid">{[['01','Leilão','Consulte informações disponíveis sobre possíveis registros de leilão.'],['02','Sinistro','Veja informações disponíveis sobre ocorrências no histórico.'],['03','Restrições','Verifique possíveis restrições associadas ao veículo.'],['04','Roubo e furto','Consulte registros disponíveis relacionados ao veículo.'],['05','Dados cadastrais','Confira informações cadastrais do veículo.'],['06','Financiamento','Consulte informações disponíveis relacionadas ao veículo.']].map(([number,title,text]) => <div className="benefit" key={title}><span>{number}</span><h3>{title}</h3><p>{text}</p><ChevronRight size={18}/></div>)}</div><Link className="text-link" href="/consultas">Ver todas as consultas <ArrowRight size={16}/></Link></section>
  <section className="section premium-section"><div className="premium-copy"><span className="eyebrow">Para uma visão mais completa</span><h2>Quer entender melhor antes de decidir?</h2><p>A Consulta Premium reúne mais pontos de verificação em uma experiência simples de ler. Um ponto de partida para quem está levando a compra a sério.</p><ul>{products[0].features.map((feature) => <li key={feature}><Check size={17}/>{feature}</li>)}</ul><div className="price-line"><strong>{products[0].price}</strong><span>por consulta</span></div><Link className="button" href="/consultas/consulta-premium">Conhecer a Premium <ArrowRight size={17}/></Link></div><div className="premium-art"><div className="premium-ring"/><div className="premium-ticket"><span>OLHO NO DOC</span><strong>PREMIUM</strong><small>Mais contexto para sua decisão</small><div className="ticket-code">ABC1D23 <span>✓</span></div></div></div></section>
  <section className="section report-section"><div className="section-heading"><div><span className="eyebrow">Resultado claro</span><h2>Veja como o resultado chega até você.</h2></div><Link className="text-link" href="/exemplo-relatorio">Ver exemplo completo <ArrowRight size={16}/></Link></div><div className="report-layout"><ReportPreview/><div className="report-aside"><span className="aside-number">01</span><h3>Sem complicação para interpretar.</h3><p>O resultado é organizado para você encontrar os pontos mais importantes da consulta e saber onde prestar atenção.</p><Link className="button button-outline" href="/exemplo-relatorio">Explorar relatório <ArrowRight size={16}/></Link></div></div></section>
  <section className="section steps-section"><div className="section-heading centered"><span className="eyebrow">Do começo ao resultado</span><h2>Consultar um veículo é simples.</h2><p>Você informa a placa, escolhe o nível de informação e recebe um relatório demonstrativo para consultar.</p></div><div className="steps">{[['01','Digite a placa','Comece pela placa do veículo que você está avaliando.'],['02','Escolha sua consulta','Compare as opções e selecione o que faz sentido para você.'],['03','Faça o pagamento','Uma etapa rápida para liberar o resultado.'],['04','Acesse o relatório','Veja as informações organizadas em poucos segundos.']].map(([n,t,d]) => <div className="step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></section>
  <section className="section products-section"><div className="section-heading"><div><span className="eyebrow">Escolha seu nível de informação</span><h2>Uma consulta para cada momento.</h2></div><Link className="text-link" href="/comparar-consultas">Comparar consultas <ArrowRight size={16}/></Link></div><div className="product-grid">{products.slice(0, 3).map((product, index) => <ProductCard key={product.slug} product={product} featured={index === 0}/>)}</div></section>
  <section className="human-section"><div className="human-image"/><div className="human-copy"><span className="eyebrow eyebrow-light">Uma decisão importante</span><h2>Não compre apenas pela aparência.</h2><p>Um veículo pode parecer perfeito e ainda ter informações importantes no histórico. Consulte antes de fechar negócio.</p><Link className="button button-light" href="/consultas">Consultar veículo <ArrowRight size={17}/></Link></div></section>
  <section className="section faq-section"><div className="section-heading"><div><span className="eyebrow">Tire suas dúvidas</span><h2>Perguntas frequentes.</h2></div><Link className="text-link" href="/faq">Ver todas as perguntas <ArrowRight size={16}/></Link></div><FAQ items={faqs}/></section>
  <section className="final-cta"><div><span className="eyebrow eyebrow-light">Sua próxima decisão começa aqui</span><h2>Vai comprar um veículo?</h2><p>Consulte antes de fechar negócio.</p></div><PlateInput dark/></section>
</>; }