'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

type Product = { id: string; slug: string; name: string; shortName: string; description: string; priceCents: number; promotionalPriceCents: number | null; status: string; featured: string; ctaText: string | null; seoTitle: string | null; seoDescription: string | null };
const money = (cents: number) => (cents / 100).toFixed(2).replace('.', ',');
export default function ProductEdit({ params }: { params: { slug: string } }) { const router = useRouter(); const [product, setProduct] = useState<Product | null>(null); const [form, setForm] = useState({ name: '', shortName: '', description: '', price: '', promotionalPrice: '', active: true, featured: false, ctaText: '', seoTitle: '', seoDescription: '' }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { fetch(`/api/admin/products/${params.slug}`).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error); const item = data.data; setProduct(item); setForm({ name: item.name, shortName: item.shortName, description: item.description, price: money(item.priceCents), promotionalPrice: item.promotionalPriceCents == null ? '' : money(item.promotionalPriceCents), active: item.status === 'ACTIVE', featured: item.featured === 'FEATURED', ctaText: item.ctaText || '', seoTitle: item.seoTitle || '', seoDescription: item.seoDescription || '' }); }).catch(e => setMessage(e.message || 'Não foi possível carregar o produto')).finally(() => setLoading(false)); }, [params.slug]);
  function set(key: string, value: string | boolean) { setForm(current => ({ ...current, [key]: value })); }
  async function save() { setSaving(true); setMessage(''); const response = await fetch(`/api/admin/products/${params.slug}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: form.name, shortName: form.shortName, description: form.description, priceCents: Math.round(Number(form.price.replace(',', '.')) * 100), promotionalPriceCents: form.promotionalPrice ? Math.round(Number(form.promotionalPrice.replace(',', '.')) * 100) : null, active: form.active, featured: form.featured, ctaText: form.ctaText, seoTitle: form.seoTitle, seoDescription: form.seoDescription }) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? 'Produto salvo com sucesso.' : data.error || 'Não foi possível salvar.'); setSaving(false); }
  if (loading) return <main className="admin-cms"><div className="admin-cms-loading">Carregando produto…</div></main>; if (!product) return <main className="admin-cms"><div className="admin-cms-message error">{message}</div></main>;
  return <main className="admin-cms"><header className="admin-cms-header"><div><span className="admin-cms-kicker">PRODUTOS / EDITAR</span><h1>{product.name}</h1><p>Edite os dados comerciais e de apresentação.</p></div><button className="admin-cms-primary" onClick={save} disabled={saving}>{saving ? 'Salvando…' : 'Salvar alterações'}</button></header>{message && <div className={`admin-cms-message ${message.includes('sucesso') ? '' : 'error'}`}>{message}</div>}<section className="admin-cms-card admin-product-editor"><div className="admin-card-heading"><div><span className="admin-eyebrow">CATÁLOGO</span><h2>Dados do produto</h2></div></div><div className="admin-form-grid"><label>Nome<input value={form.name} onChange={e => set('name', e.target.value)}/></label><label>Nome curto<input value={form.shortName} onChange={e => set('shortName', e.target.value)}/></label><label className="wide">Descrição<textarea rows={4} value={form.description} onChange={e => set('description', e.target.value)}/></label><label>Preço normal (R$)<input inputMode="decimal" value={form.price} onChange={e => set('price', e.target.value)}/></label><label>Preço promocional (R$)<input inputMode="decimal" placeholder="Opcional" value={form.promotionalPrice} onChange={e => set('promotionalPrice', e.target.value)}/></label><label>Texto do botão<input value={form.ctaText} onChange={e => set('ctaText', e.target.value)}/></label><label className="admin-check-field"><input type="checkbox" checked={form.active} onChange={e => set('active', e.target.checked)}/> Produto ativo</label><label className="admin-check-field"><input type="checkbox" checked={form.featured} onChange={e => set('featured', e.target.checked)}/> Produto em destaque</label><label className="wide">Título SEO<input value={form.seoTitle} onChange={e => set('seoTitle', e.target.value)}/></label><label className="wide">Descrição SEO<textarea rows={3} value={form.seoDescription} onChange={e => set('seoDescription', e.target.value)}/></label></div></section></main>;
}
