'use client';

import { FormEvent, useEffect, useState } from 'react';

type Product = { slug: string; name: string };

export default function BonusConsultationPage() {
  const [products, setProducts] = useState<Product[]>([]);
  const [form, setForm] = useState({ name: '', email: '', phone: '', cpf: '', plate: '', productSlug: '', reason: '' });
  const [result, setResult] = useState<{ orderId: string; temporaryPassword: string; emailSent: boolean } | null>(null);
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => { fetch('/api/admin/products').then(async response => { const body = await response.json(); if (response.ok) setProducts(body.data || body || []); }).catch(() => undefined); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); setResult(null); try { const response = await fetch('/api/admin/bonuses', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Não foi possível criar a bonificação.'); setResult(body.data); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao criar bonificação.'); } finally { setLoading(false); } }
  return <main className="admin-cms"><header className="admin-cms-header"><div><span className="admin-cms-kicker">OPERAÇÃO / CONSULTAS</span><h1>Consulta bonificada</h1><p>Libere uma consulta sem cobrança para um cliente atendido pela equipe.</p></div></header><section className="admin-panel-card"><form className="admin-form-grid" onSubmit={submit}><label>Nome do cliente<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></label><label>E-mail<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/></label><label>WhatsApp<input required value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })}/></label><label>CPF<input required value={form.cpf} onChange={e => setForm({ ...form, cpf: e.target.value })}/></label><label>Placa<input required value={form.plate} onChange={e => setForm({ ...form, plate: e.target.value.toUpperCase() })}/></label><label>Produto<select required value={form.productSlug} onChange={e => setForm({ ...form, productSlug: e.target.value })}><option value="">Selecione</option>{products.map(product => <option key={product.slug} value={product.slug}>{product.name}</option>)}</select></label><label className="wide">Motivo da bonificação<textarea required minLength={5} rows={3} value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })}/></label><div className="wide"><button className="admin-cms-primary" disabled={loading}>{loading ? 'Criando…' : 'Criar consulta bonificada'}</button></div></form>{error && <div className="admin-cms-message error">{error}</div>}{result && <div className="admin-cms-message success"><strong>Pedido criado:</strong> {result.orderId}<br/><strong>Senha temporária:</strong> {result.temporaryPassword}<br/>{result.emailSent ? 'Instruções enviadas por e-mail.' : 'Envio de e-mail indisponível; entregue a senha por canal seguro.'}</div>}</section></main>;
}
