'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Check, LoaderCircle, Trash2, UserPlus } from 'lucide-react';

export default function AdminPanel({ currentEmail }: { currentEmail: string | null }) {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [inviteCode, setInviteCode] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [users, setUsers] = useState<Array<{ id: string; name: string | null; username: string | null; email: string | null; role: string }>>([]);
  async function loadUsers() { const response = await fetch('/api/admin/users'); if (response.ok) { const data = await response.json(); setUsers(data.data); } }
  useEffect(() => { loadUsers(); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setMessage(''); setLoading(true); const response = await fetch('/api/admin/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, email, inviteCode }) }); const data = await response.json(); setLoading(false); if (!response.ok) { setError(data.error || 'Não foi possível cadastrar.'); return; } setMessage(`${data.data.email} agora pode acessar a área administrativa por código de e-mail.`); setName(''); setEmail(''); setInviteCode(''); }
  async function removeUser(id: string) { if (!window.confirm('Excluir este usuário e todos os dados vinculados? Esta ação não pode ser desfeita.')) return; setError(''); const response = await fetch(`/api/admin/users/${id}`, { method: 'DELETE' }); const data = await response.json(); if (!response.ok) { setError(data.error || 'Não foi possível excluir.'); return; } setMessage(data.message); loadUsers(); }
  return <section className="admin-section"><div className="admin-overview"><div className="admin-stat"><span>Conta ativa</span><strong>{currentEmail || 'Acesso sem e-mail'}</strong><small>SUPERADMIN</small></div><div className="admin-stat"><span>Próximos módulos</span><strong>Produtos e pedidos</strong><small>Estrutura preparada</small></div></div><div className="admin-card"><div className="admin-card-title"><div><span className="eyebrow">Controle de acesso</span><h2>Cadastrar administrador</h2><p>O novo administrador receberá acesso usando o próprio e-mail. Nenhuma senha é armazenada.</p></div><UserPlus size={25}/></div><form className="admin-form" onSubmit={submit}><label>Nome<input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Nome do administrador"/></label><label>E-mail<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="admin@seudominio.com"/></label><label className="wide">Código de cadastro<input required value={inviteCode} onChange={(event) => setInviteCode(event.target.value)} placeholder="Código configurado no EasyPanel"/></label>{error && <p className="auth-message auth-error">{error}</p>}{message && <p className="auth-message auth-success"><Check size={16}/> {message}</p>}<button className="button" disabled={loading}>{loading ? <LoaderCircle className="spin" size={17}/> : <UserPlus size={17}/>}Cadastrar administrador</button></form></div><div className="admin-card admin-users-card"><div className="admin-card-title"><div><span className="eyebrow">Contas cadastradas</span><h2>Usuários e administradores</h2></div></div><div className="admin-users-list">{users.map((user) => <div className="admin-user-row" key={user.id}><div><strong>{user.name || user.username || user.email || 'Sem identificação'}</strong><small>{user.email || user.username || 'Sem e-mail'} · {user.role}</small></div>{user.id !== '' && <button className="icon-danger" onClick={() => removeUser(user.id)} title="Excluir usuário" aria-label="Excluir usuário"><Trash2 size={17}/></button>}</div>)}</div></div></section>;
}