'use client';

import { FormEvent, useState } from 'react';
import { Check, LoaderCircle, UserPlus } from 'lucide-react';

export default function AdminPanel({ currentEmail }: { currentEmail: string | null }) {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [inviteCode, setInviteCode] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setMessage(''); setLoading(true); const response = await fetch('/api/admin/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, email, inviteCode }) }); const data = await response.json(); setLoading(false); if (!response.ok) { setError(data.error || 'Não foi possível cadastrar.'); return; } setMessage(`${data.data.email} agora pode acessar a área administrativa por código de e-mail.`); setName(''); setEmail(''); setInviteCode(''); }
  return <section className="admin-section"><div className="admin-overview"><div className="admin-stat"><span>Conta ativa</span><strong>{currentEmail || 'Acesso sem e-mail'}</strong><small>SUPERADMIN</small></div><div className="admin-stat"><span>Próximos módulos</span><strong>Produtos e pedidos</strong><small>Estrutura preparada</small></div></div><div className="admin-card"><div className="admin-card-title"><div><span className="eyebrow">Controle de acesso</span><h2>Cadastrar administrador</h2><p>O novo administrador receberá acesso usando o próprio e-mail. Nenhuma senha é armazenada.</p></div><UserPlus size={25}/></div><form className="admin-form" onSubmit={submit}><label>Nome<input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Nome do administrador"/></label><label>E-mail<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="admin@seudominio.com"/></label><label className="wide">Código de cadastro<input required value={inviteCode} onChange={(event) => setInviteCode(event.target.value)} placeholder="Código configurado no EasyPanel"/></label>{error && <p className="auth-message auth-error">{error}</p>}{message && <p className="auth-message auth-success"><Check size={16}/> {message}</p>}<button className="button" disabled={loading}>{loading ? <LoaderCircle className="spin" size={17}/> : <UserPlus size={17}/>}Cadastrar administrador</button></form></div></section>;
}