'use client';

import { FormEvent, useEffect, useState } from 'react';
import { Check, LoaderCircle, ShieldCheck, Trash2, UserPlus } from 'lucide-react';

async function responseData(response: Response) { const text = await response.text(); try { return text ? JSON.parse(text) : {}; } catch { return {}; } }

type User = { id: string; name: string | null; username: string | null; email: string | null; role: string };

export default function AdminPanel({ currentEmail }: { currentEmail: string | null }) {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [users, setUsers] = useState<User[]>([]);
  async function loadUsers() { try { const response = await fetch('/api/admin/users'); const data = await responseData(response); if (!response.ok) { setError(data.error || 'Não foi possível carregar os usuários.'); return; } setUsers(data.data || []); } catch { setError('Não foi possível conectar ao servidor.'); } }
  useEffect(() => { loadUsers(); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); setMessage(''); setLoading(true); try { const response = await fetch('/api/admin/users', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, email, password }) }); const data = await responseData(response); if (!response.ok) { setError(data.error || 'Não foi possível cadastrar.'); return; } setMessage(`${data.data.email} foi cadastrado como administrador.`); setName(''); setEmail(''); setPassword(''); await loadUsers(); } catch { setError('Não foi possível conectar ao servidor.'); } finally { setLoading(false); } }
  async function promote(id: string) { setError(''); setMessage(''); try { const response = await fetch(`/api/admin/users/${id}`, { method: 'PATCH' }); const data = await responseData(response); if (!response.ok) { setError(data.error || 'Não foi possível promover.'); return; } setMessage('Conta promovida para SUPERADMIN.'); await loadUsers(); } catch { setError('Não foi possível conectar ao servidor.'); } }
  async function removeUser(id: string) { if (!window.confirm('Excluir este usuário e todos os dados vinculados? Esta ação não pode ser desfeita.')) return; setError(''); try { const response = await fetch(`/api/admin/users/${id}`, { method: 'DELETE' }); const data = await responseData(response); if (!response.ok) { setError(data.error || 'Não foi possível excluir.'); return; } setMessage(data.message); await loadUsers(); } catch { setError('Não foi possível conectar ao servidor.'); } }
  return <section className="admin-section"><div className="admin-overview"><div className="admin-stat"><span>Conta ativa</span><strong>{currentEmail || 'Acesso sem e-mail'}</strong><small>SUPERADMIN</small></div><div className="admin-stat"><span>Próximos módulos</span><strong>Produtos e pedidos</strong><small>Estrutura preparada</small></div></div><div className="admin-card"><div className="admin-card-title"><div><span className="eyebrow">Controle de acesso</span><h2>Cadastrar administrador</h2><p>A conta usará o e-mail e a senha cadastrados. Depois, você poderá promovê-la a SUPERADMIN.</p></div><UserPlus size={25}/></div><form className="admin-form" onSubmit={submit}><label>Nome<input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Nome do administrador"/></label><label>E-mail<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="admin@seudominio.com"/></label><label>Senha<input required type="password" minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Mínimo de 8 caracteres"/></label>{error && <p className="auth-message auth-error">{error}</p>}{message && <p className="auth-message auth-success"><Check size={16}/> {message}</p>}<button className="button" disabled={loading}>{loading ? <LoaderCircle className="spin" size={17}/> : <UserPlus size={17}/>}Cadastrar administrador</button></form></div><div className="admin-card admin-users-card"><div className="admin-card-title"><div><span className="eyebrow">Contas cadastradas</span><h2>Usuários e administradores</h2></div></div><div className="admin-users-list">{users.map((user) => <div className="admin-user-row" key={user.id}><div><strong>{user.name || user.username || user.email || 'Sem identificação'}</strong><small>{user.email || user.username || 'Sem e-mail'} · {user.role}</small></div><div className="admin-user-actions">{user.role === 'ADMIN' && <button className="icon-promote" onClick={() => promote(user.id)} title="Promover para superadmin" aria-label="Promover para superadmin"><ShieldCheck size={17}/></button>}{user.id !== '' && <button className="icon-danger" onClick={() => removeUser(user.id)} title="Excluir usuário" aria-label="Excluir usuário"><Trash2 size={17}/></button>}</div></div>)}</div></div></section>;
}
