'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Bell, ChevronDown, LayoutDashboard, LogOut, Menu, Search, Settings, ShieldCheck, Users, X } from 'lucide-react';
import { useState } from 'react';
import { usePathname } from 'next/navigation';

const sections = [
  { label: 'VISÃO GERAL', items: [{ href: '/admin', label: 'Dashboard', icon: LayoutDashboard }] },
  { label: 'COMERCIAL', items: [{ href: '/admin/clientes', label: 'Clientes', icon: Users }, { href: '/admin/leads', label: 'Leads', icon: Users }, { href: '/admin/carrinhos-abandonados', label: 'Carrinhos abandonados', icon: LayoutDashboard }, { href: '/admin/recuperacoes', label: 'Recuperações', icon: LayoutDashboard }] },
  { label: 'OPERAÇÃO', items: [{ href: '/admin/consultas', label: 'Consultas realizadas', icon: LayoutDashboard }, { href: '/admin/fornecedores', label: 'Fornecedores', icon: Settings }] },
  { label: 'VENDAS', items: [{ href: '/admin/pedidos', label: 'Pedidos', icon: LayoutDashboard }, { href: '/admin/pagamentos', label: 'Pagamentos', icon: LayoutDashboard }] },
  { label: 'PRODUTOS', items: [{ href: '/admin/produtos', label: 'Consultas', icon: LayoutDashboard }, { href: '/admin/caracteristicas', label: 'Características', icon: Settings }, { href: '/admin/precos', label: 'Preços', icon: LayoutDashboard }, { href: '/admin/cupons', label: 'Cupons', icon: LayoutDashboard }] },
  { label: 'SITE', items: [{ href: '/admin/site/home', label: 'Home', icon: LayoutDashboard }, { href: '/admin/site/paginas', label: 'Páginas', icon: LayoutDashboard }, { href: '/admin/site/menu', label: 'Menu', icon: LayoutDashboard }, { href: '/admin/site/rodape', label: 'Rodapé', icon: LayoutDashboard }, { href: '/admin/site/banners', label: 'Banners', icon: LayoutDashboard }, { href: '/admin/site/midias', label: 'Mídias', icon: LayoutDashboard }] },
  { label: 'CONTEÚDO', items: [{ href: '/admin/blog', label: 'Blog', icon: LayoutDashboard }, { href: '/admin/categorias', label: 'Categorias', icon: LayoutDashboard }, { href: '/admin/faq', label: 'FAQ', icon: LayoutDashboard }] },
  { label: 'MARKETING', items: [{ href: '/admin/campanhas', label: 'Campanhas', icon: LayoutDashboard }, { href: '/admin/utms', label: 'UTMs', icon: LayoutDashboard }, { href: '/admin/templates', label: 'Templates', icon: LayoutDashboard }, { href: '/admin/automacoes', label: 'Automações', icon: Settings }] },
  { label: 'SEO', items: [{ href: '/admin/seo', label: 'Visão geral SEO', icon: LayoutDashboard }, { href: '/admin/seo/redirecionamentos', label: 'Redirecionamentos', icon: LayoutDashboard }, { href: '/admin/seo/scripts', label: 'Scripts / Pixels', icon: Settings }] },
  { label: 'RELATÓRIOS', items: [{ href: '/admin/relatorios/funil', label: 'Funil', icon: LayoutDashboard }, { href: '/admin/relatorios/conversao', label: 'Conversão', icon: LayoutDashboard }] },
  { label: 'SISTEMA', items: [{ href: '/admin/marca', label: 'Marca', icon: ShieldCheck }, { href: '/admin/usuarios', label: 'Usuários', icon: Users }, { href: '/admin/usuarios', label: 'Permissões', icon: ShieldCheck }, { href: '/admin/integracoes', label: 'Integrações', icon: Settings }, { href: '/admin/configuracoes', label: 'Configurações', icon: Settings }, { href: '/admin/consultas', label: 'Logs operacionais', icon: LayoutDashboard }] }
];

export function AdminSidebar() { const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const pathname = usePathname(); return <><aside className={`admin-sidebar ${collapsed ? 'collapsed' : ''} ${mobileOpen ? 'mobile-open' : ''}`}><div className="admin-sidebar-brand"><Link href="/admin" aria-label="Dashboard Olho no Doc"><img src="/logo-olho-no-doc.png" alt="Olho no Doc"/></Link><button className="admin-sidebar-close" onClick={() => setMobileOpen(false)} aria-label="Fechar menu"><X size={18}/></button></div><nav>{sections.map((section) => <div className="admin-nav-group" key={section.label}><span className="admin-nav-label">{section.label}</span>{section.items.map(({ href, label, icon: Icon }) => <Link href={href} className={`admin-nav-item ${pathname === href || (href !== '/admin' && pathname.startsWith(`${href}/`)) ? 'active' : ''}`} key={href} title={collapsed ? label : undefined} onClick={() => setMobileOpen(false)}><Icon size={17}/><span>{label}</span></Link>)}</div>)}</nav><button className="admin-collapse" onClick={() => setCollapsed(!collapsed)} aria-label={collapsed ? 'Expandir menu' : 'Recolher menu'}><ChevronDown size={16}/><span>{collapsed ? 'Expandir' : 'Recolher menu'}</span></button></aside><button className="admin-mobile-toggle" onClick={() => setMobileOpen(true)} aria-label="Abrir menu"><Menu size={21}/></button></>; }

export function AdminTopbar({ name }: { name: string }) { const router = useRouter(); async function logout() { await fetch('/api/auth/logout', { method: 'POST' }); router.replace('/login'); router.refresh(); } return <header className="admin-topbar"><div className="admin-global-search"><Search size={17}/><input placeholder="Buscar cliente, placa, pedido ou consulta..." aria-label="Busca global"/></div><div className="admin-topbar-actions"><select aria-label="Período"><option>Hoje</option><option>Ontem</option><option>7 dias</option><option>30 dias</option><option>90 dias</option></select><button aria-label="Notificações"><Bell size={18}/><span className="notification-dot"/></button><div className="admin-profile"><span>{name.slice(0, 1).toUpperCase()}</span><strong>{name}</strong><button className="admin-logout" onClick={logout} aria-label="Sair"><LogOut size={15}/> Sair</button></div></div></header>; }

export function AdminShell({ children, name }: { children: React.ReactNode; name: string }) { return <div className="admin-app"><AdminSidebar/><div className="admin-main"><AdminTopbar name={name}/><main className="admin-content">{children}</main></div></div>; }
