import Link from 'next/link';
import { ArrowRight, Check, ChevronRight } from 'lucide-react';
import { FAQ, PlateInput, ProductCard, ReportPreview } from '@/components/site';
import { Product, products } from '@/data/products';

export function PageHero({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <section className="page-hero"><div className="page-hero-inner"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div></section>; }

export function ProductDetail({ product }: { product: Product }) { return <><PageHero eyebrow={`Consultas / ${product.shortName}`} title={product.name} description={product.description}/><section className="detail-intro"><div><span className="eyebrow">Comece pela placa</span><h2>Mais clareza para a sua próxima decisão.</h2><p>{product.useCase}</p><PlateInput/></div><div className="detail-price"><span>Por consulta</span><strong>{product.price}</strong><Link className="button" href="/consultas">Escolher esta consulta <ArrowRight size={16}/></Link></div></section><section className="section detail-section"><div className="section-heading"><div><span className="eyebrow">O que esta consulta verifica</span><h2>Informação organizada para você avaliar.</h2></div></div><div className="detail-features">{product.features.map((feature, index) => <div key={feature}><span>0{index + 1}</span><Check size={18}/><h3>{feature}</h3><p>Informação demonstrativa apresentada de forma clara no relatório.</p></div>)}</div></section><section className="section detail-report"><div><span className="eyebrow">Prévia do resultado</span><h2>Veja o tipo de informação que você recebe.</h2><p>Este é um exemplo visual. Os dados exibidos são fictícios e servem apenas para demonstrar a experiência.</p></div><ReportPreview/></section><section className="section detail-compare"><span className="eyebrow">Ainda em dúvida?</span><h2>Compare com outras consultas.</h2><p>Encontre o nível de informação mais adequado para o momento da sua compra.</p><Link className="text-link" href="/comparar-consultas">Comparar consultas <ArrowRight size={16}/></Link></section><section className="final-cta"><div><span className="eyebrow eyebrow-light">Consulte antes de comprar</span><h2>Pronto para começar?</h2><p>Informe a placa do veículo que você está avaliando.</p></div><PlateInput dark/></section></>; }

export function ProductCatalog() { return <><PageHero eyebrow="Consultas veiculares" title="Consultas para diferentes momentos da sua decisão." description="Escolha a consulta que oferece as informações que você precisa para avaliar um veículo."/><section className="section catalog-section"><div className="product-grid">{products.map((product, index) => <ProductCard key={product.slug} product={product} featured={index === 0}/>)}</div></section><section className="section simple-band"><span className="eyebrow">Uma escolha mais consciente</span><h2>Compare as opções antes de consultar.</h2><Link className="button" href="/comparar-consultas">Comparar consultas <ArrowRight size={16}/></Link></section></>; }

export function GenericContent({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) { return <><PageHero eyebrow={eyebrow} title={title} description={description}/><section className="section generic-content">{children}</section></>; }

export const comparisonRows = ['Dados cadastrais', 'Leilão', 'Sinistro', 'Roubo e furto', 'Restrições', 'Financiamento', 'Outras informações'];
export function Comparison() { return <><PageHero eyebrow="Escolha com contexto" title="Encontre a consulta ideal para o que você precisa verificar." description="Compare as opções do Olho no Doc e escolha o nível de informação que faz sentido para sua decisão."/><section className="section comparison-section"><div className="comparison-table"><div className="comparison-head"><span>O que você verifica</span>{products.map((product) => <strong key={product.slug}>{product.shortName}<small>{product.price}</small></strong>)}</div>{comparisonRows.map((row, index) => <div className="comparison-row" key={row}><span>{row}</span>{products.map((product) => <span key={product.slug} className={index < (product.slug === 'consulta-premium' ? 6 : product.slug === 'consulta-essencial' ? 3 : 2) ? 'yes' : ''}>{index < (product.slug === 'consulta-premium' ? 6 : product.slug === 'consulta-essencial' ? 3 : 2) ? '✓' : '—'}</span>)}</div>)}</div></section><section className="simple-band"><span className="eyebrow">A opção mais completa</span><h2>Veja tudo o que a Consulta Premium reúne.</h2><Link className="button" href="/consultas/consulta-premium">Conhecer a Premium <ArrowRight size={16}/></Link></section></>; }