'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
import type { CatalogProduct } from '@/lib/catalog';

export default function CheckoutForm({ product, plate }: { product: CatalogProduct; plate: string }) {
  const [address, setAddress] = useState({ postalCode: '', street: '', number: '', complement: '', neighborhood: '', city: '', state: '' }); const [cpf, setCpf] = useState(''); const [phone, setPhone] = useState(''); const [error, setError] = useState(''); const [order, setOrder] = useState<{ orderId: string; amountCents: number | null } | null>(null); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { const response = await fetch('/api/checkout/prepare', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ productSlug: product.slug, plate, cpf, phone, address }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setOrder(body.data); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível preparar o checkout.'); } finally { setLoading(false); } }
  if (order) return <main className="checkout-page"><section className="checkout-card"><span className="eyebrow">PEDIDO PREPARADO</span><h1>Seu pedido está pronto para pagamento.</h1><p>Pedido {order.orderId.slice(-8).toUpperCase()} criado como pendente. A confirmação de pagamento será conectada na próxima etapa; a consulta ainda não foi enviada à Company.</p><Link href="/minha-conta" className="button">Ir para minha conta</Link></section></main>;
  return <main className="checkout-page"><div className="checkout-shell"><section className="checkout-card"><span className="eyebrow">ETAPA 2 · ENDEREÇO</span><h1>Finalize os dados da sua compra.</h1><p>Agora que você escolheu <strong>{product.name}</strong> para a placa <strong>{plate}</strong>, precisamos do endereço para preparar o pedido.</p><form onSubmit={submit}><div className="checkout-grid"><label>CPF<input required value={cpf} onChange={e => setCpf(e.target.value)} placeholder="000.000.000-00"/></label><label>WhatsApp<input required type="tel" value={phone} onChange={e => setPhone(e.target.value)} placeholder="(00) 00000-0000"/></label>{[['postalCode','CEP'],['street','Rua'],['number','Número'],['complement','Complemento'],['neighborhood','Bairro'],['city','Cidade'],['state','UF']].map(([key,label]) => <label key={key}>{label}<input required={key !== 'complement'} value={address[key as keyof typeof address]} onChange={e => setAddress({ ...address, [key]: e.target.value })} maxLength={key === 'state' ? 2 : undefined}/></label>)}</div>{error && <p className="form-error">{error}</p>}<button className="button" disabled={loading}>{loading ? 'Preparando…' : 'Continuar para pagamento'}</button></form></section><aside className="checkout-summary"><span className="eyebrow">RESUMO</span><h2>{product.name}</h2><p>Placa: <strong>{plate || 'Não informada'}</strong></p><strong className="checkout-price">{product.price}</strong><small>O pagamento ainda será conectado.</small></aside></div></main>;
}
