'use client';

import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, LoaderCircle } from 'lucide-react';
import { FormEvent, useState } from 'react';

export default function LoginPage() {
	const [step, setStep] = useState<'email' | 'code' | 'register'>('email'); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [code, setCode] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
	async function requestCode(event: FormEvent) { event.preventDefault(); setError(''); setMessage(''); setLoading(true); const response = await fetch('/api/auth/request-code', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, email }) }); const data = await response.json(); setLoading(false); if (!response.ok) { setError(data.error || 'Não foi possível enviar o código.'); return; } setMessage(data.message); setStep('code'); }
	async function register(event: FormEvent) { event.preventDefault(); setError(''); setLoading(true); const response = await fetch('/api/auth/register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name, email }) }); const data = await response.json(); setLoading(false); if (!response.ok) { setError(data.error || 'Não foi possível criar sua conta.'); return; } window.location.href = new URLSearchParams(window.location.search).get('next') || '/consultas'; }
	async function verifyCode(event: FormEvent) { event.preventDefault(); setError(''); setLoading(true); const response = await fetch('/api/auth/verify-code', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, code }) }); const data = await response.json(); setLoading(false); if (!response.ok) { setError(data.error || 'Código inválido.'); return; } window.location.href = new URLSearchParams(window.location.search).get('next') || '/consultas'; }
	return <section className="auth-page"><div className="auth-box auth-box-wide"><Link href="/" className="auth-back"><ArrowLeft size={15}/> Voltar para o início</Link><span className="eyebrow">Área do cliente</span>{step === 'register' ? <><h1>Crie seu cadastro.</h1><p>No primeiro acesso, basta informar seus dados. O código de e-mail será ativado em uma próxima etapa.</p><form onSubmit={register}><label>Nome completo<input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Seu nome" autoComplete="name"/></label><label>E-mail<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="voce@email.com" autoComplete="email"/></label>{error && <p className="auth-message auth-error">{error}</p>}<button className="button" disabled={loading}>{loading ? <LoaderCircle className="spin" size={17}/> : <Check size={17}/>}Criar cadastro</button></form><button className="auth-change" onClick={() => { setStep('email'); setError(''); }}>Já tenho cadastro</button></> : step === 'email' ? <><h1>Entre na sua conta.</h1><p>Use seu e-mail para receber um código de acesso.</p><form onSubmit={requestCode}><label>E-mail<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="voce@email.com" autoComplete="email"/></label>{error && <p className="auth-message auth-error">{error}</p>}<button className="button" disabled={loading}>{loading ? <LoaderCircle className="spin" size={17}/> : <ArrowRight size={17}/>}Receber código por e-mail</button></form><button className="auth-change" onClick={() => { setStep('register'); setError(''); }}>Primeiro acesso? Criar cadastro</button><Link href="/admin" className="admin-login-link">Acesso administrativo</Link></> : <><h1>Confira seu e-mail.</h1><p>{message || `Enviamos um código de acesso para ${email}.`}</p><form onSubmit={verifyCode}><label>Código de verificação<input required inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ''))} placeholder="000000" autoComplete="one-time-code"/></label>{error && <p className="auth-message auth-error">{error}</p>}<button className="button" disabled={loading}>{loading ? <LoaderCircle className="spin" size={17}/> : <Check size={17}/>}Confirmar e entrar</button></form><button className="auth-change" onClick={() => { setStep('email'); setCode(''); setError(''); }}>Usar outro e-mail</button></>}</div></section>;
}