'use client';
import { useEffect, useState } from 'react';

type Order = { id: string; plate: string; status: string; amountCents: number; discountCents: number; totalCents: number | null; createdAt: string; product: { name: string }; customer: { name: string | null; email: string } | null };
const currency = (cents: number) => (cents / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
export default function AdminPaymentsPage() { const [orders, setOrders] = useState<Order[]>([]); const [error, setError] = useState('');
  useEffect(() => { fetch('/api/admin/orders').then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setOrders(body.data); }).catch(e => setError(e.message)); }, []);
  const pending = orders.filter(order => order.status === 'PENDING'); const paid = orders.filter(order => ['PAID', 'COMPLETED'].includes(order.status));
  return <main className="admin-cms"><header className="admin-cms-header"><div><span className="admin-cms-kicker">VENDAS / FINANCEIRO</span><h1>Pagamentos</h1><p>Acompanhe valores pendentes, pagos e integração futura do provedor.</p></div></header>{error && <div className="admin-cms-message error">{error}</div>}<section className="admin-order-summary"><span>Pendentes: <strong>{pending.length}</strong></span><span>Pagos/concluídos: <strong>{paid.length}</strong></span><span>Total pago: <strong>{currency(paid.reduce((total, order) => total + (order.totalCents ?? order.amountCents), 0))}</strong></span></section><div className="admin-order-table"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Pedido</th><th>Valor</th><th>Desconto</th><th>Status pagamento</th></tr></thead><tbody>{orders.map(order => <tr key={order.id}><td><strong>{order.id.slice(-8).toUpperCase()}</strong><small>{new Date(order.createdAt).toLocaleDateString('pt-BR')}</small></td><td>{order.customer?.name || 'Cliente'}<small>{order.customer?.email || order.plate}</small></td><td>{order.product.name}</td><td><strong>{currency(order.totalCents ?? order.amountCents)}</strong></td><td>{currency(order.discountCents)}</td><td><span className={`admin-order-status ${order.status.toLowerCase()}`}>{order.status === 'PENDING' ? 'AGUARDANDO PAGAMENTO' : order.status === 'CANCELLED' ? 'CANCELADO' : 'PAGO'}</span></td></tr>)} {!orders.length && <tr><td colSpan={6}>Nenhum pagamento encontrado.</td></tr>}</tbody></table></div><section className="admin-cms-card admin-payment-note"><h2>Integração do provedor</h2><p>Os status acima são derivados do pedido. O webhook do provedor será conectado nesta mesma tela após a definição do gateway.</p></section></main>;
}
