'use client';
import { useEffect, useState } from 'react';

type Supplier = { id: string; name: string; type: string; endpoint: string; status: string; notes: string };
const empty = { name: '', type: 'Dados veiculares', endpoint: '', notes: '' };
export default function SuppliersPage() { const [items, setItems] = useState<Supplier[]>([]); const [form, setForm] = useState(empty); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch('/api/admin/suppliers').then(async response => { const body = await response.json(); if (response.ok) setItems(body.data); }); }, []);
  async function save(next: Supplier[]) { setSaving(true); setMessage(''); const response = await fetch('/api/admin/suppliers', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(next) }); const body = await response.json().catch(() => ({})); if (response.ok) { setItems(body.data); setMessage('Fornecedores salvos.'); } else setMessage(body.error || 'Não foi possível salvar.'); setSaving(false); }
  function add() { if (!form.name || !form.endpoint) return; save([...items, { ...form, id: crypto.randomUUID(), status: 'ATIVO' }]); setForm(empty); }
  return <main className="admin-cms"><header className="admin-cms-header"><div><span className="admin-cms-kicker">OPERAÇÃO / INTEGRAÇÕES</span><h1>Fornecedores</h1><p>Registre os provedores de dados usados nas consultas.</p></div></header>{message && <div className="admin-cms-message">{message}</div>}<section className="admin-cms-card admin-supplier-form"><h2>Novo fornecedor</h2><div className="admin-form-grid"><label>Nome<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="DataCheck"/></label><label>Tipo<input value={form.type} onChange={e => setForm({ ...form, type: e.target.value })}/></label><label className="wide">Endpoint API<input value={form.endpoint} onChange={e => setForm({ ...form, endpoint: e.target.value })} placeholder="https://api.fornecedor.com/v1"/></label><label className="wide">Observações<textarea rows={2} value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })}/></label></div><button className="admin-cms-primary" onClick={add} disabled={saving}>Adicionar e salvar</button></section><section className="admin-cms-card"><h2>Integrações cadastradas</h2><div className="admin-order-table"><table><thead><tr><th>Fornecedor</th><th>Tipo</th><th>Endpoint</th><th>Status</th><th>Ações</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.notes || '—'}</small></td><td>{item.type}</td><td>{item.endpoint}</td><td><span className={`admin-order-status ${item.status === 'ATIVO' ? 'completed' : 'cancelled'}`}>{item.status}</span></td><td><div className="admin-table-actions"><button onClick={() => save(items.map(current => current.id === item.id ? { ...current, status: current.status === 'ATIVO' ? 'INATIVO' : 'ATIVO' } : current))}>{item.status === 'ATIVO' ? 'Desativar' : 'Ativar'}</button><button onClick={() => save(items.filter(current => current.id !== item.id))}>Excluir</button></div></td></tr>)}{items.length === 0 && <tr><td colSpan={5}>Nenhum fornecedor cadastrado.</td></tr>}</tbody></table></div></section></main>;
}
