'use client';

import { FormEvent, useEffect, useState } from 'react';
import { AdminPageHeader } from '@/components/admin-primitives';
import { Check, Mail, Save, Send, ShieldCheck } from 'lucide-react';

type Config = { host: string; port: number; user: string; from: string; secure: boolean; passwordConfigured: boolean };
const empty: Config = { host: '', port: 587, user: '', from: '', secure: false, passwordConfigured: false };

export default function AdminSettingsPage() {
  const [config, setConfig] = useState<Config>(empty); const [password, setPassword] = useState(''); const [testEmail, setTestEmail] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [testing, setTesting] = useState(false);
  useEffect(() => { fetch('/api/admin/settings?key=email.smtp').then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setConfig(body); }).catch((e) => setError(e.message)); }, []);
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); setMessage(''); try { const response = await fetch('/api/admin/settings', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ key: 'email.smtp', value: { ...config, password: password || undefined } }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setConfig(body); setPassword(''); setMessage('Configuração SMTP salva com segurança.'); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível salvar.'); } finally { setSaving(false); } }
  async function test() { setTesting(true); setError(''); setMessage(''); try { const response = await fetch('/api/admin/settings', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'test-email', email: testEmail }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setMessage(body.message); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível enviar o teste.'); } finally { setTesting(false); } }
  return <div><AdminPageHeader eyebrow="Sistema / Configurações" title="E-mail e SMTP" description="Configure o canal usado para recuperação de senha e futuros avisos da plataforma."/><div className="admin-users-notice"><ShieldCheck size={18}/><div><strong>Credencial protegida</strong><p>A senha SMTP é criptografada antes de ser armazenada e nunca é exibida novamente. A chave SMTP_ENCRYPTION_KEY deve existir no ambiente.</p></div></div>{error && <div className="admin-users-feedback error">{error}</div>}{message && <div className="admin-users-feedback success"><Check size={16}/>{message}</div>}<section className="admin-panel-card admin-settings-card"><div className="admin-card-heading"><div><span className="admin-eyebrow">ENVIO DE E-MAIL</span><h2>Servidor SMTP</h2></div><Mail size={22}/></div><form onSubmit={save}><div className="admin-form-grid"><label>Servidor<input required value={config.host} onChange={(e) => setConfig({ ...config, host: e.target.value })} placeholder="smtp.seuprovedor.com"/></label><label>Porta<input required type="number" min={1} max={65535} value={config.port} onChange={(e) => setConfig({ ...config, port: Number(e.target.value) })}/></label><label>Usuário<input required value={config.user} onChange={(e) => setConfig({ ...config, user: e.target.value })} autoComplete="username"/></label><label>E-mail remetente<input required type="email" value={config.from} onChange={(e) => setConfig({ ...config, from: e.target.value })}/></label><label className="wide">Senha SMTP<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder={config.passwordConfigured ? 'Senha já configurada · informe apenas para trocar' : 'Senha do servidor SMTP'} autoComplete="new-password"/></label><label className="admin-settings-check"><input type="checkbox" checked={config.secure} onChange={(e) => setConfig({ ...config, secure: e.target.checked })}/> Usar conexão segura (TLS/SSL)</label></div><button className="admin-primary-button" disabled={saving}>{saving ? 'Salvando…' : <><Save size={15}/> Salvar SMTP</>}</button></form></section><section className="admin-panel-card admin-settings-card"><div className="admin-card-heading"><div><span className="admin-eyebrow">VALIDAÇÃO</span><h2>Enviar e-mail de teste</h2><p>Confirme se a configuração consegue entregar uma mensagem.</p></div><Send size={22}/></div><div className="admin-settings-test"><input type="email" placeholder="destino@exemplo.com" value={testEmail} onChange={(e) => setTestEmail(e.target.value)}/><button className="admin-secondary-button" onClick={test} disabled={testing || !testEmail}>{testing ? 'Enviando…' : 'Enviar teste'}</button></div></section></div>;
}
