'use client';
import { FormEvent, useEffect, useState } from 'react';

type AdminQuery = { id: string; normalizedPlate: string; queriedAt: string; order: { id: string; plate: string; status: string; product: { name: string }; customer: { name: string | null; email: string } | null } };
export default function AdminQueriesPage() { const [queries, setQueries] = useState<AdminQuery[]>([]); const [plate, setPlate] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  async function load(search = '') { setLoading(true); setError(''); try { const response = await fetch(`/api/admin/queries${search ? `?plate=${encodeURIComponent(search)}` : ''}`); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || 'Não foi possível carregar consultas'); setQueries(body.data); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao carregar'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  function search(event: FormEvent) { event.preventDefault(); load(plate.trim()); }
  return <main className="admin-cms"><header className="admin-cms-header"><div><span className="admin-cms-kicker">OPERAÇÃO / CONSULTAS</span><h1>Consultas realizadas</h1><p>Pesquise por placa e acompanhe as consultas executadas.</p></div><form className="admin-order-table-search" onSubmit={search}><input className="admin-input" placeholder="ABC1D23" value={plate} onChange={e => setPlate(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 7))}/><button className="admin-cms-primary" type="submit">Buscar</button></form></header><div className="admin-order-summary"><span>Consultas: <strong>{queries.length}</strong></span></div>{error && <div className="admin-cms-message error">{error}</div>}<div className="admin-order-table"><table><thead><tr><th>Pedido</th><th>Placa</th><th>Cliente</th><th>Produto</th><th>Status</th><th>Data</th></tr></thead><tbody>{!loading && queries.map(query => <tr key={query.id}><td><strong>{query.order.id.slice(-8).toUpperCase()}</strong></td><td>{query.normalizedPlate}</td><td>{query.order.customer?.name || 'Cliente'}<small>{query.order.customer?.email || '—'}</small></td><td>{query.order.product.name}</td><td><span className={`admin-order-status ${query.order.status.toLowerCase()}`}>{query.order.status}</span></td><td>{new Date(query.queriedAt).toLocaleString('pt-BR')}</td></tr>)}{!loading && queries.length === 0 && <tr><td colSpan={6}>Nenhuma consulta encontrada.</td></tr>}{loading && <tr><td colSpan={6}>Carregando consultas…</td></tr>}</tbody></table></div></main>;
}
