'use client';
import { useEffect, useState } from 'react';

type RecoveryOrder = { id: string; plate: string; status: string; amountCents: number; totalCents: number | null; createdAt: string; product: { name: string }; customer: { name: string | null; email: string } | null };
const currency = (cents: number) => (cents / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' });
export default function AdminRecoveryPage() { const [pending, setPending] = useState<RecoveryOrder[]>([]); const [cancelled, setCancelled] = useState<RecoveryOrder[]>([]); const [error, setError] = useState('');
  useEffect(() => { fetch('/api/admin/recovery').then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setPending(body.data.pending); setCancelled(body.data.cancelled); }).catch(e => setError(e.message)); }, []);
  const pendingTotal = pending.reduce((total, order) => total + (order.totalCents ?? order.amountCents), 0);
  return <main className="admin-cms"><header className="admin-cms-header"><div><span className="admin-cms-kicker">COMERCIAL / RECUPERAÇÃO</span><h1>Carrinhos abandonados</h1><p>Priorize pedidos pendentes e cancelados para recuperação.</p></div></header>{error && <div className="admin-cms-message error">{error}</div>}<section className="admin-order-summary"><span>Pendentes: <strong>{pending.length}</strong></span><span>Valor recuperável: <strong>{currency(pendingTotal)}</strong></span><span>Cancelados: <strong>{cancelled.length}</strong></span></section><section className="admin-cms-card admin-recovery-card"><h2>Pedidos pendentes</h2><div className="admin-order-table"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Produto / placa</th><th>Valor</th><th>Data</th></tr></thead><tbody>{pending.map(order => <tr key={order.id}><td><strong>{order.id.slice(-8).toUpperCase()}</strong></td><td>{order.customer?.name || 'Cliente'}<small>{order.customer?.email || '—'}</small></td><td>{order.product.name}<small>{order.plate}</small></td><td><strong>{currency(order.totalCents ?? order.amountCents)}</strong></td><td>{new Date(order.createdAt).toLocaleString('pt-BR')}</td></tr>)}{pending.length === 0 && <tr><td colSpan={5}>Nenhum carrinho abandonado.</td></tr>}</tbody></table></div></section><section className="admin-cms-card admin-recovery-card"><h2>Pedidos cancelados</h2><div className="admin-order-table"><table><thead><tr><th>Pedido</th><th>Cliente</th><th>Produto / placa</th><th>Valor</th></tr></thead><tbody>{cancelled.map(order => <tr key={order.id}><td><strong>{order.id.slice(-8).toUpperCase()}</strong></td><td>{order.customer?.name || 'Cliente'}<small>{order.customer?.email || '—'}</small></td><td>{order.product.name}<small>{order.plate}</small></td><td><strong>{currency(order.totalCents ?? order.amountCents)}</strong></td></tr>)}{cancelled.length === 0 && <tr><td colSpan={4}>Nenhum pedido cancelado.</td></tr>}</tbody></table></div></section></main>;
}
