'use client';
import { useEffect, useState } from 'react';
type Entry = { id: string; question: string; answer: string; status: string; sortOrder: number };
export default function FaqAdminPage() { const [items, setItems] = useState<Entry[]>([]); const [question, setQuestion] = useState(''); const [answer, setAnswer] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [removingId, setRemovingId] = useState('');
 async function load() { const response = await fetch('/api/admin/content?kind=faq'); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Não foi possível carregar as perguntas.'); setItems(body.data); }
 useEffect(() => { load().catch(e => setError(e instanceof Error ? e.message : 'Não foi possível carregar as perguntas.')); }, []);
 async function create() { setSaving(true); setError(''); try { const response = await fetch('/api/admin/content', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ kind: 'faq', question, answer }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Não foi possível adicionar a pergunta.'); setQuestion(''); setAnswer(''); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível adicionar a pergunta.'); } finally { setSaving(false); } }
 async function remove(id: string) { setRemovingId(id); setError(''); try { const response = await fetch(`/api/admin/content/${id}?kind=faq`, { method: 'DELETE' }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Não foi possível excluir.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Não foi possível excluir.'); } finally { setRemovingId(''); } }
 return <main className="admin-cms"><header className="admin-cms-header"><div><span className="admin-cms-kicker">CONTEÚDO / FAQ</span><h1>Perguntas frequentes</h1><p>Gerencie as perguntas exibidas aos visitantes.</p></div></header>{error && <div className="admin-cms-message error">{error}</div>}<section className="admin-cms-card"><h2>Adicionar pergunta</h2><div className="admin-form-grid"><label className="wide">Pergunta<input value={question} onChange={e => setQuestion(e.target.value)}/></label><label className="wide">Resposta<textarea rows={4} value={answer} onChange={e => setAnswer(e.target.value)}/></label></div><button className="admin-cms-primary" onClick={create} disabled={saving || !question.trim() || !answer.trim()}>{saving ? 'Adicionando…' : 'Adicionar'}</button></section><section className="admin-cms-card"><h2>FAQ cadastrado</h2>{items.map(item => <article className="admin-faq-row" key={item.id}><div><strong>{item.question}</strong><p>{item.answer}</p></div><button onClick={() => remove(item.id)} disabled={removingId === item.id}>{removingId === item.id ? 'Excluindo…' : 'Excluir'}</button></article>)}{items.length === 0 && <p>Nenhuma pergunta cadastrada.</p>}</section></main>;
}
