'use client';

import { useEffect, useState } from 'react';

type Brand = Record<string, string>;
const defaults: Brand = { name: 'Olho no Doc', tagline: 'Sua tranquilidade é nosso foco.', logoLight: '/logo-olho-no-doc.png', logoDark: '/logo-olho-no-doc.png', primary: '#061b2f', accent: '#18c887', email: '', phone: '' };

async function readResponse(response: Response) { const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Não foi possível concluir a operação.'); return data; }

export default function BrandPage() {
  const [brand, setBrand] = useState<Brand>(defaults); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { fetch('/api/admin/settings?key=brand').then(readResponse).then((data) => setBrand({ ...defaults, ...(data || {}) })).catch((e) => setError(e.message)).finally(() => setLoading(false)); }, []);
  const set = (key: string, value: string) => { setBrand({ ...brand, [key]: value }); setMessage(''); setError(''); };
  async function save() { setSaving(true); setMessage(''); setError(''); try { const saved = await readResponse(await fetch('/api/admin/settings', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ key: 'brand', value: brand }) })); setBrand({ ...defaults, ...saved }); setMessage('Alterações salvas com sucesso.'); } catch (e) { setError(e instanceof Error ? e.message : 'Erro ao salvar.'); } finally { setSaving(false); } }
  if (loading) return <main className="admin-cms"><div className="admin-cms-loading">Carregando identidade da marca…</div></main>;
  return <main className="admin-cms"><header className="admin-cms-header"><div><span className="admin-cms-kicker">SISTEMA / MARCA</span><h1>Identidade da marca</h1><p>Defina como a marca aparece no site público.</p></div><button className="admin-cms-primary" onClick={save} disabled={saving}>{saving ? 'Salvando…' : 'Salvar alterações'}</button></header>{message && <div className="admin-cms-message success">{message}</div>}{error && <div className="admin-cms-message error">{error}</div>}
    <div className="admin-brand-layout"><section className="admin-cms-card"><div className="admin-cms-card-heading"><div><span className="admin-cms-kicker">IDENTIDADE VISUAL</span><h2>Marca e aparência</h2></div><span className="admin-cms-card-badge">PUBLICADO</span></div><div className="admin-cms-form-grid"><label>Nome da marca<input value={brand.name || ''} onChange={(e) => set('name', e.target.value)} /></label><label>Slogan<input value={brand.tagline || ''} onChange={(e) => set('tagline', e.target.value)} /></label></div><div className="admin-logo-grid"><LogoField label="Logo para fundo claro" value={brand.logoDark} onChange={(value) => set('logoDark', value)} /><LogoField label="Logo para fundo escuro" value={brand.logoLight} onChange={(value) => set('logoLight', value)} dark /></div></section>
      <aside className="admin-cms-card admin-brand-preview"><span className="admin-cms-kicker">PRÉVIA</span><h2>Veja sua marca</h2><div className="brand-preview-stage" style={{ background: brand.primary || defaults.primary }}><img src={brand.logoLight || defaults.logoLight} alt="Logo em fundo escuro" onError={(e) => { e.currentTarget.src = defaults.logoLight; }} /><span>{brand.tagline}</span></div><div className="brand-preview-stage light" style={{ background: brand.accent || defaults.accent }}><img src={brand.logoDark || defaults.logoDark} alt="Logo em fundo claro" onError={(e) => { e.currentTarget.src = defaults.logoDark; }} /></div></aside>
      <section className="admin-cms-card"><div className="admin-cms-card-heading"><div><span className="admin-cms-kicker">PALETA</span><h2>Cores da marca</h2></div></div><div className="admin-color-grid"><ColorField label="Cor principal" value={brand.primary} onChange={(value) => set('primary', value)} /><ColorField label="Cor de ação" value={brand.accent} onChange={(value) => set('accent', value)} /></div></section>
      <section className="admin-cms-card"><div className="admin-cms-card-heading"><div><span className="admin-cms-kicker">CONTATO</span><h2>Informações públicas</h2></div></div><div className="admin-cms-form-grid"><label>E-mail<input type="email" value={brand.email || ''} onChange={(e) => set('email', e.target.value)} placeholder="contato@seudominio.com" /></label><label>Telefone<input value={brand.phone || ''} onChange={(e) => set('phone', e.target.value)} placeholder="(00) 00000-0000" /></label></div></section></div>
  </main>;
}
function LogoField({ label, value, onChange, dark = false }: { label: string; value?: string; onChange: (value: string) => void; dark?: boolean }) { return <div className="admin-logo-field"><div className={`admin-logo-preview ${dark ? 'dark' : ''}`}><img src={value || defaults.logoDark} alt={label} onError={(e) => { e.currentTarget.style.display = 'none'; }} /><span>Prévia da logo</span></div><label>{label}<input value={value || ''} onChange={(e) => onChange(e.target.value)} placeholder="https://... ou /logo.png" /><small>Use uma URL pública de imagem PNG, JPG ou SVG.</small></label></div>; }
function ColorField({ label, value, onChange }: { label: string; value?: string; onChange: (value: string) => void }) { const color = /^#[0-9a-f]{6}$/i.test(value || '') ? value : '#061b2f'; return <label className="admin-color-field">{label}<div><input type="color" value={color} onChange={(e) => onChange(e.target.value)} /><input value={value || ''} onChange={(e) => onChange(e.target.value)} placeholder="#061b2f" /></div></label>; }
